import type { BlogPost } from "@/components/pages/product/blog/types";

export const posts: BlogPost[] = [
  {
    slug: "geo-vs-seo",
    title: "GEO is not SEO with a new acronym",
    dek: "Citation share, answer position, and sentiment — the metrics marketing teams need when buyers decide inside the chat.",
    date: "Jul 22",
    year: "2026",
    publishedAt: "2026-07-22",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "There's a debate that's been running for two years: is it GEO, AI search optimization, or just SEO? One camp insists nothing changed. The other wants to declare SEO dead. Both miss the point." },
    { type: "p", text: "SEO isn't finished — and it isn't unchanged. Ranking still matters because AI engines ground answers in traditional search. What's stacked on top of that pipeline is new enough that teams who only run the old playbook leave half the opportunity on the table." },
    { type: "h2", text: "AI search is a decision channel, not a traffic channel" },
    { type: "p", text: "Classic Google Search optimizes for pages people will click and stay on. Ten blue links. Rank, earn the click, convert on your funnel." },
    { type: "p", text: "ChatGPT, AI Overviews, and Gemini aren't trying to send someone somewhere. They're trying to be the answer. Buyers often decide inside the chat without hitting your landing page or seeing the brand system you spent months polishing. That makes mentions and citability first-class work — not a side project for the SEO team." },
    { type: "h2", text: "The ranking pipeline got more steps" },
    { type: "p", text: "Traditional search was roughly: index, then rank. AI search keeps that foundation and adds layers: grounding in web results, training-data familiarity, and citability — being selected as a source after you've already been retrieved." },
    { type: "ul", items: ["Grounding still leans on classic ranking. Falling out of traditional search removes you from the AI layer too.","Training data shapes who the model already 'knows' before it searches.","Citability is separate from retrieval. You can rank, get pulled as a candidate, and still never be named."] },
    { type: "h2", text: "From websites to brands" },
    { type: "p", text: "Models lean hard on third-party sources — Reddit, YouTube, review sites, Wikipedia — depending on the query. Your official site is often a small slice of the answer. Incorrect claims sitting in competitor content get repeated as confidently as true ones. Off-domain reputation work is now part of the job." },
    { type: "h2", text: "Measurement looks like brand marketing" },
    { type: "p", text: "Performance marketing spoiled us with tagged clicks. AI search removes the click. When the decisive moment happens in chat, first- and last-click models miss it. What's left looks like share of voice: how often, and how favorably, models mention you versus competitors across the prompts that matter." },
    { type: "h2", text: "Demand data is sparse and skewed" },
    { type: "p", text: "Prompt-volume tools rarely come from the AI engines themselves. They're often reconstructed from clickstream harvested via free extensions — not your enterprise buyers. Build prompt sets from your real customer journey instead of chasing inflated volume numbers." },
    { type: "h2", text: "Visibility differs by model" },
    { type: "p", text: "A brand can dominate ChatGPT and disappear in AI Mode. Fanout behavior, training data, and system prompts diverge. Track ChatGPT, Gemini, AI Overviews, and AI Mode as separate surfaces — Anny was built for that split." },
    { type: "h2", text: "So — GEO or SEO?" },
    { type: "p", text: "Call it whatever you want. The foundation is shared; the surface area is not. Manage training presence, citations, brand mentions, and model-by-model gaps — or watch competitors who do." },
    ],
  },
  {
    slug: "ai-mode-changed-the-serp",
    title: "AI Mode changed the SERP — here's what to measure now",
    dek: "Why classic rank trackers miss the answers that actually drive clicks and trust — and why AI Overviews deserve equal attention.",
    date: "Jul 21",
    year: "2026",
    publishedAt: "2026-07-21",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Google AI Overviews reached roughly 2.5 billion monthly users — larger than ChatGPT, Claude, and Perplexity combined. In commercial, buying-intent prompt samples, Overviews appear around 87% of the time. Yet most GEO conversations still orbit ChatGPT." },
    { type: "p", text: "If your tracking stack ignores Overviews and AI Mode, you're under-measuring the surface where most buyers already see AI-assisted answers." },
    { type: "h2", text: "It shows up for commercial queries too" },
    { type: "p", text: "The myth that Overviews are 'informational only' doesn't hold. Decision-stage prompts — comparisons, best-of, product research — trigger Overviews at least as often as top-of-funnel questions. When someone searches 'best CRM for small business,' Google is already summarizing options and leaving brands out." },
    { type: "h2", text: "Intent shape matters more than funnel label" },
    { type: "p", text: "Clear linguistic patterns (definitions, comparisons, how-tos, yes/no) see Overviews in the mid-90% range. Vague fragments drop closer to two-thirds. Longer, conversational queries trigger Overviews more often than two-word keywords — another reason keyword-only trackers miss the shift." },
    { type: "h2", text: "Markets aren't identical" },
    { type: "p", text: "EU rates run lower than non-EU (roughly mid-70s vs ~90%), and some markets (notably France at times) have limited or no Overviews. Still, 76% appearance is not 'optional.' Treat it as default search UX wherever it's live." },
    { type: "h2", text: "Google is stitching one chat experience" },
    { type: "p", text: "Overviews, AI Mode, and Gemini are converging. Follow-ups from an Overview can route into AI Mode. Tracking one Google AI surface and ignoring the others understates your exposure." },
    { type: "h2", text: "Optimize differently than ChatGPT" },
    { type: "ul", items: ["YouTube carries outsized weight in Google's AI surfaces.","ChatGPT often struggles with JS-heavy pages; Google renders more of them.","ChatGPT leans on query fanouts and Reciprocal Rank Fusion — presence across related angles beats winning one keyword.","Reddit shows up everywhere. Community presence isn't optional."] },
    { type: "h2", text: "What to track in Anny" },
    { type: "ol", items: ["AI Overviews — where most searchers get AI answers","AI Mode — growing fast and connected to Overviews","ChatGPT — still culturally dominant, different ranking logic","Gemini — source chips and citation patterns of its own"] },
    { type: "p", text: "You don't need to optimize everything at once. You do need data on where you stand. Gaps you don't measure don't get fixed." },
    ],
  },
  {
    slug: "chatgpt-mentions-playbook",
    title: "A playbook for earning ChatGPT brand mentions",
    dek: "Prompt clusters, source gaps, and the content shapes models cite most often when they recommend brands.",
    date: "Jul 8",
    year: "2026",
    publishedAt: "2026-07-08",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Brand mentions in ChatGPT aren't a traffic channel first — they're a recommendation channel. Someone asks for options; your name either appears or it doesn't. Clicks are optional. Influence is not." },
    { type: "h2", text: "Cover the journey, not just 'best X'" },
    { type: "p", text: "Most teams only track consideration prompts. That's incomplete. Build clusters for awareness (category fears and objections), consideration (best-of and segment variants), evaluation (Brand vs Brand, 'is X worth it?'), and purchase where you sell direct." },
    { type: "h2", text: "Win the sources ChatGPT already trusts" },
    { type: "p", text: "Mentions often come from third-party pages the model retrieves — listicles, reviews, Reddit, Wikipedia — not from your homepage. Find prompts where competitors appear and you don't, then identify the URLs driving those answers. Prioritize sources that show up across multiple models." },
    { type: "h2", text: "Meet the fanouts halfway" },
    { type: "p", text: "ChatGPT secretly reframes advice queries with words like best, reviews, comparison, and the current year. Structure pages to answer those angles: ratings summaries, tradeoffs, segment-specific recommendations, fresh dates." },
    { type: "h2", text: "Fix sentiment sources fast" },
    { type: "p", text: "A toxic review site or outdated comparison can poison evaluation-stage answers. Visibility without favorable sentiment loses deals. Monitor how models describe you, then correct the underlying pages." },
    { type: "h2", text: "Measure the right KPIs" },
    { type: "ul", items: ["Visibility % across tagged prompt groups","Answer position when you appear","Sentiment on evaluation prompts","Self-reported 'how did you hear about us?' including AI"] },
    { type: "p", text: "Anny is built around these loops — prompt libraries, competitor ladders, source gap views, and sentiment — so the playbook isn't a slide deck, it's a weekly operating system." },
    ],
  },
  {
    slug: "agency-visibility-retainers",
    title: "How agencies package AI visibility retainers",
    dek: "Reporting cadences and white-label scorecards that clients actually open — without building internal tooling.",
    date: "Jun 9",
    year: "2026",
    publishedAt: "2026-06-09",
    category: "Agencies",
    body: [
    { type: "p", text: "Clients don't buy 'GEO theory.' They buy proof they're showing up in AI answers — and a plan when they aren't. Agencies that win package tracking, narrative, and action into a retainer clients understand." },
    { type: "h2", text: "What the retainer usually includes" },
    { type: "ul", items: ["Prompt libraries mapped to each client's journey stages","Weekly or biweekly visibility, position, and sentiment trends","Competitor ladders and source/mention gap lists","A short action backlog: listicle outreach, review fixes, content refreshes"] },
    { type: "h2", text: "Pricing that sticks" },
    { type: "p", text: "Published 2026 benchmarks put tracking-and-reporting retainers around $1,500–$2,500 per client per month, and full GEO programs with content and earned media at $2,500–$6,000. Many agencies start by adding 20–30% to an existing SEO retainer instead of inventing a new line item." },
    { type: "h2", text: "Reporting clients open" },
    { type: "p", text: "One slide per client beats a 40-page PDF. Lead with: where they gained or lost mentions this week, which sources drove competitor wins, and the three actions you'll take. Automate the pull via API or MCP into Slack plus a white-label deck." },
    { type: "h2", text: "White-label without the overhead" },
    { type: "p", text: "Anny agency plans include isolated client workspaces, unlimited seats, white-label dashboards, and API access. You resell under your brand; Anny stays under the hood. Same-week launch is realistic when onboarding covers prompt libraries and report templates." },
    { type: "h2", text: "The weekly loop" },
    { type: "ol", items: ["Refresh answers across ChatGPT, Gemini, and AI Mode","Diff visibility and sentiment vs last period","Push a one-pager + Slack summary","Ship 1–3 source or content actions"] },
    { type: "p", text: "That's the product. Everything else is packaging." },
    ],
  },
  {
    slug: "gemini-source-chips",
    title: "Reading Gemini's source chips like a marketer",
    dek: "Which domains stick across turns, and how to get yours into the shortlist when Gemini answers.",
    date: "May 27",
    year: "2026",
    publishedAt: "2026-05-27",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Gemini doesn't just answer — it shows source chips that reveal which domains shaped the response. Treat those chips as a live map of influence for your category." },
    { type: "h2", text: "What the chips tell you" },
    { type: "ul", items: ["Which publishers Gemini trusts for this prompt type","Whether brand sites or UGC (Reddit, YouTube, Medium) dominate","Whether your domain was retrieved but not elevated"] },
    { type: "h2", text: "Patterns that keep showing up" },
    { type: "p", text: "Across multi-engine citation studies, Reddit and YouTube sit near the top for Gemini alongside Wikipedia and editorial sites. Review platforms matter for software and services. Your industry's 'Booking.com equivalent' may outrank generic top-10 lists — always check category-specific domains in Anny's source view." },
    { type: "h2", text: "How to act on a chip shortlist" },
    { type: "ol", items: ["Tag prompts by intent and product line","Export domains Gemini cites when competitors win","Prioritize multi-model overlaps (Gemini + ChatGPT + Perplexity)","Pursue inclusion or correction on those URLs"] },
    { type: "h2", text: "Don't optimize blind" },
    { type: "p", text: "A chip that appears once is noise. A domain that recurs across commercial prompts is a campaign target. Track chip stability week over week — Anny's Gemini visibility views are built for that habit." },
    ],
  },
  {
    slug: "complete-guide-to-geo",
    title: "The complete guide to Generative Engine Optimization",
    dek: "How to measure brand presence in AI answers, optimize for retrieval and citation, and build the external footprint models actually use.",
    date: "Aug 27",
    year: "2025",
    publishedAt: "2025-08-27",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Buyers increasingly get answers from AI before they ever see your site. Zero-click behavior was already high in classic search; AI Mode and ChatGPT push it further. Traffic doesn't vanish — it concentrates into fewer, higher-intent visits. GEO is the framework for capturing visibility when the answer is the product." },
    { type: "h2", text: "Two systems: foundation models vs RAG" },
    { type: "p", text: "Foundation models are trained, then frozen. Influencing them is a long game of web presence that ends up in future training sets. Retrieval-augmented generation (RAG) is where you can move this quarter: when models search live, they retrieve, rank, chunk, and cite." },
    { type: "p", text: "Query fanouts mean the model searches multiple related queries, not just the user's exact words. Optimize for the angles behind the prompt." },
    { type: "h2", text: "Two success metrics" },
    { type: "ul", items: ["Brand visibility — your name appears in the answer (awareness without a click).","Website citations — your URLs are used as sources (traffic + authority)."] },
    { type: "p", text: "You can be mentioned without being cited, or cited without being named. Track both." },
    { type: "h2", text: "External presence often beats your homepage" },
    { type: "p", text: "What others say about you on the sources models retrieve frequently matters as much as what you publish. Map those sources, then earn accurate mentions." },
    { type: "h2", text: "A four-phase loop" },
    { type: "ol", items: ["Source analysis — where do models pull for your topics?","Optimization — content structure + off-site presence","Assessment — visibility and citation rate over time","Refinement — iterate on gaps"] },
    { type: "h2", text: "Content that gets retrieved" },
    { type: "p", text: "Clear headings, extractable facts, comparisons, and listicles that cover multiple options in one page tend to outperform thin single-product blurbs. Keep pages fresh — models inject the current year into fanouts. Serve content without relying solely on client-side JavaScript for critical copy." },
    { type: "h2", text: "Start this week" },
    { type: "ul", items: ["Baseline visibility in Anny across your priority prompts","Segment LLM referral traffic in analytics (knowing it's incomplete)","Map the source landscape for five commercial prompts","Pick one high-gap third-party URL for outreach"] },
    { type: "p", text: "GEO won't replace SEO. It extends it into the answer layer where decisions increasingly happen." },
    ],
  },
  {
    slug: "measure-ai-search-visibility-kpis",
    title: "How to measure AI search visibility: the KPIs that matter",
    dek: "Visibility, position, sentiment, and imperfect revenue signals — a practical measurement stack when clicks disappear.",
    date: "Mar 11",
    year: "2026",
    publishedAt: "2026-03-11",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "AI search already recommends brands before a site visit. Many teams still aren't measuring it — or they're measuring traffic from LLMs and calling it done. Traffic is useful and incomplete. Here's what actually works." },
    { type: "h2", text: "Visibility percentage" },
    { type: "p", text: "What share of relevant answers include your brand? Split prompts by topic, funnel stage, and segment. Single-prompt noise is high; category-level trends are stable. Track weekly aggregates." },
    { type: "h2", text: "Answer position" },
    { type: "p", text: "Being tenth on a 'best of' list is not the same as being first. Position drives attention inside the answer. Aggregate across prompts — day-to-day ranks swing." },
    { type: "h2", text: "Brand sentiment" },
    { type: "p", text: "Visibility tells you if you're in the room. Sentiment tells you what the model says once you're there. Evaluation prompts ('Is X reliable?') are where sentiment hits revenue. Fix toxic sources early." },
    { type: "h2", text: "Revenue and attribution" },
    { type: "p", text: "Ask how customers found you — on demos, signup, or post-purchase. Self-reported AI discovery plus cohort revenue beats pretending UTMs catch chat influence. Pair with LLM-referred sessions, knowing most AI-influenced journeys still convert after a Google or direct visit." },
    { type: "h2", text: "Expert consensus, roughly" },
    { type: "quote", text: "Stop using traffic as the only KPI. Blend AI visibility, sentiment, purchases, and revenue — and track visibility at a topical level through the journey, not only as individual prompts.", cite: "Industry practitioners across SEO and GEO" },
    { type: "h2", text: "Start now" },
    { type: "p", text: "Imperfect frameworks beat another quarter of anecdotes. Anny surfaces visibility, position, sentiment, and sources so you can defend the budget with evidence leadership recognizes." },
    ],
  },
  {
    slug: "choose-prompts-for-llm-tracking",
    title: "How to choose the right prompts for LLM tracking",
    dek: "Stop chasing prompt volume. Build coverage across awareness, consideration, evaluation, and the segments you actually sell to.",
    date: "Jan 22",
    year: "2026",
    publishedAt: "2026-01-22",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "In classic SEO, keyword volume pointed at a plan. In AI search, one buying decision spans many prompts — and personalization means the same words can yield different answers for different people. Volume alone won't cut it." },
    { type: "h2", text: "Three coverage axes" },
    { type: "ul", items: ["Journey stage — awareness, consideration, evaluation/purchase","Customer context — segments, constraints, use cases","Geography — if you sell in multiple markets"] },
    { type: "h2", text: "Awareness" },
    { type: "p", text: "Catch category fears before brand shortlists form. Pull objections from sales calls, Reddit, and 'what concerns do people have about [category]?' Turn them into prompts: reliability, cost, fit for families, cold weather, and so on." },
    { type: "h2", text: "Consideration" },
    { type: "p", text: "Track broad 'best X' prompts and segment variants ('best X for small teams'). Include plain category nouns — people still type them." },
    { type: "h2", text: "Purchase and evaluation" },
    { type: "p", text: "Ecommerce needs 'where to buy' coverage. Everyone needs brand evaluation tracked separately ('Brand A vs Brand B') so 100% visibility on branded prompts doesn't inflate your averages." },
    { type: "h2", text: "Fast start without deep discovery" },
    { type: "ol", items: ["Convert top non-branded GSC queries into natural questions","Read the site nav and pricing tiers for segments","Draft 10–20 awareness + 20–30 consideration prompts","Track 30 days in Anny, then fill gaps where competitors dominate"] },
    { type: "p", text: "Winning teams cover the journey strategically. They don't track everything — they track the moments that decide deals." },
    ],
  },
  {
    slug: "source-gap-analysis",
    title: "A beginner's guide to source gap analysis in AI search",
    dek: "Use citation rate to find pages that get retrieved but rarely cited — then redesign them like models prefer.",
    date: "Jan 30",
    year: "2026",
    publishedAt: "2026-01-26",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Citations are how publications and brand sites earn credit inside AI answers. Retrieval alone isn't enough — the model can fetch your URL and still never use it." },
    { type: "h2", text: "Four buckets of source performance" },
    { type: "ol", items: ["Not retrieved — SEO fundamentals first","Retrieved but never cited — format and extractability issues","Retrieved but rarely cited — the gap analysis sweet spot","Retrieved and cited often — protect and extend"] },
    { type: "h2", text: "Citation rate benchmarks (directional)" },
    { type: "ul", items: ["ChatGPT: aiming above ~2.0 average citations per answer is strong","Google AI Mode: ~1.1–1.5 is a fair target; the distribution is tighter","Perplexity: selective — ~1.5–2.0 puts you in rare company"] },
    { type: "h2", text: "What tends to get cited" },
    { type: "p", text: "On ChatGPT, well-structured listicles covering multiple products often outperform thin single-item reviews. AI Mode leans more toward official product and category pages. Tag prompts by intent so commercial queries aren't mixed with trivia." },
    { type: "h2", text: "Actions for content teams" },
    { type: "ul", items: ["Add clear H-tags, bullets, and a summary up top","Roll single reviews into hub listicles","Refresh URLs that already get retrieved","Retest citation rate in Anny after changes"] },
    ],
  },
  {
    slug: "brand-mention-gap-analysis",
    title: "A beginner's guide to brand mention gap analysis",
    dek: "Find prompts where competitors appear and you don't — then close the gap on the sources driving those answers.",
    date: "Feb 5",
    year: "2026",
    publishedAt: "2026-02-05",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Citation-first strategies chase URLs. Mention-first strategies chase your brand name in the answer — even without a link. Both matter; this note is about mentions." },
    { type: "h2", text: "The workflow" },
    { type: "ol", items: ["Track prompts with tags and competitors (including aliases)","Filter high-intent prompts where you're absent","Inspect sources sorted by usage and competitor mentions","Prioritize URLs that appear across multiple AI models","Outreach: organic, paid, PR, or review campaigns","Watch visibility lift in Anny over the following weeks"] },
    { type: "h2", text: "Why multi-model overlap matters" },
    { type: "p", text: "A Forbes-style roundup cited by both ChatGPT and Perplexity is worth more than a one-off blog. Gap score thinking — competitor mentions × source usage — keeps outreach queues honest." },
    { type: "h2", text: "Mention vs citation" },
    { type: "p", text: "You can close mention gaps via third-party coverage without owning the domain. Pair this with source gap work on your own URLs for a full program." },
    ],
  },
  {
    slug: "brand-sentiment-in-llms",
    title: "Ultimate guide to tracking brand sentiment in LLMs",
    dek: "Visibility without favorable framing loses deals. How to monitor what models say — and fix the sources that poison answers.",
    date: "Jan 23",
    year: "2026",
    publishedAt: "2026-01-23",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "When a prospect asks 'Is this brand reliable?' the answer they get can close or kill the deal. Sentiment tracking is one of the highest-ROI GEO habits because many negative drivers are fixable pages — not frozen training data." },
    { type: "h2", text: "What to track" },
    { type: "ul", items: ["Evaluation prompts: support quality, pricing fairness, reliability, 'is it worth it'","Competitor contrast prompts","Recurring phrases models use about you"] },
    { type: "h2", text: "Find the source of the framing" },
    { type: "p", text: "Models often aren't inventing criticism — they're repeating review sites, Reddit threads, or outdated articles. Identify which URLs get retrieved on negative answers. Correct factual errors, solicit legitimate reviews, and add clearer first-party pages for contested claims." },
    { type: "h2", text: "Separate metrics" },
    { type: "p", text: "Don't bury sentiment inside a single visibility score. A brand can be highly visible and poorly framed. Anny tracks sentiment alongside mention rate so weekly reports show both." },
    { type: "h2", text: "Operating cadence" },
    { type: "ol", items: ["Weekly scan of evaluation-prompt sentiment","Ticket any new toxic source","Outreach or content fix within the sprint","Confirm the answer tone improves"] },
    ],
  },
  {
    slug: "chatgpt-query-fanouts",
    title: "Patterns we see in ChatGPT query fanouts",
    dek: "Hidden sub-searches explain why listicles and reviews win — and how ChatGPT, Perplexity, and Grok diverge.",
    date: "May 5",
    year: "2026",
    publishedAt: "2026-05-05",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "If your content only answers the literal question typed, you miss what the model actually searches. Those hidden queries are fanouts — and they're one of the highest-leverage GEO signals." },
    { type: "h2", text: "Why fanouts matter" },
    { type: "p", text: "ChatGPT blends scores across subqueries (Reciprocal Rank Fusion). Content that matches multiple fanout angles beats content that matches one. Cover comparisons, reviews, brands, and year-stamped variants when the category warrants it." },
    { type: "h2", text: "Words ChatGPT injects" },
    { type: "p", text: "Top additions include best, top, comparison, reviews, tools, software, features. Advice-style prompts trigger 'best of' reframes roughly a quarter of the time. Reviews get searched even when the user never asked." },
    { type: "h2", text: "Model differences" },
    { type: "ul", items: ["Perplexity (~1.4 fanouts): often simplifies the query — weak optimization signal","ChatGPT (~2.1): adds brands, comparisons, reviews","Grok (~6.8): research-brief style, often with site:reddit / Wirecutter / G2 style targeting"] },
    { type: "h2", text: "What to do" },
    { type: "ul", items: ["Inspect fanouts for your tracked prompts in Anny","Rewrite pages to cover injected angles","Keep high-citation URLs freshly dated","Watch review-site portrayals — they leak into answers"] },
    ],
  },
  {
    slug: "chatgpt-fanouts-doubled",
    title: "ChatGPT fan-outs have doubled in length",
    dek: "Across ~20M fanouts, average query length roughly doubled — specificity is the new ranking battleground.",
    date: "Feb 12",
    year: "2026",
    publishedAt: "2026-02-12",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "From late 2025 into early 2026, average ChatGPT fanout length roughly doubled (about 6 words → ~12), consistently across countries and languages. The number of fanouts per prompt stayed roughly flat — ChatGPT got more precise per search, not noisier." },
    { type: "h2", text: "Why it matters" },
    { type: "p", text: "Longer fanouts retrieve more long-tail results and give embedding matchers more context. Broad, generic pages struggle. Detailed pages that match specific intents win retrieval." },
    { type: "h2", text: "Why it's happening" },
    { type: "ul", items: ["Retrieval stacks reward richer queries","AI-generated web content saturation pushes models toward sharper filters"] },
    { type: "h2", text: "Team takeaway" },
    { type: "p", text: "Track fanout text over time in Anny. When the hidden queries get more specific, your content brief should too. Treat this as a global architectural shift — not a local experiment." },
    ],
  },
  {
    slug: "chatgpt-searches-in-english",
    title: "ChatGPT searches in English, even when you don't",
    dek: "Nearly half of research steps for non-English prompts still hit the English web — local leaders can disappear at home.",
    date: "Feb 12",
    year: "2026",
    publishedAt: "2026-02-12",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Ask in German, Polish, or Spanish from the matching country, and ChatGPT still runs a large share of fanouts in English. Local market leaders can be missing or buried while global brands win." },
    { type: "h2", text: "What the data shows" },
    { type: "ul", items: ["A large majority of non-English sessions include at least one English sub-search","Roughly 40%+ of fanout steps for non-English prompts run on the English web","Rates vary by language but stay high everywhere studied"] },
    { type: "h2", text: "What to do" },
    { type: "ol", items: ["See which English sources ChatGPT cites in your category","Compare competitor English footprints","Invest strategically — key product pages, English listicles, review profiles — not blind full-site translation"] },
    { type: "p", text: "Anny's source and fanout views make the English bias visible so localization budgets follow evidence." },
    ],
  },
  {
    slug: "llms-txt-helper-or-hoax",
    title: "llms.txt & .md files: helpful for agents, not a GEO silver bullet",
    dek: "What Jeremy Howard's proposal actually does — and why duplicating your blog as markdown won't buy ChatGPT rankings.",
    date: "Jul 30",
    year: "2025",
    publishedAt: "2025-07-30",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "llms.txt is a curated markdown map of important pages for AI agents. It is not robots.txt, not a sitemap replacement, and — critically — major answer engines have not announced support for it as a ranking lever." },
    { type: "h2", text: "When it helps" },
    { type: "p", text: "If you want coding agents and tool-using LLMs to understand your API, docs, and workflows, a tight llms.txt (and optionally llms-full.txt) is a good bet. Anny's own AI instructions and docs follow that spirit." },
    { type: "h2", text: "When it's a distraction" },
    { type: "p", text: "Auto-generating llms.txt that dumps every SEO landing page, or cloning every article to .md duplicates, creates crawl and duplicate-content risk without proven GEO upside. Google's John Mueller has publicly compared it to the keywords meta tag: claims without confirmed consumers." },
    { type: "h2", text: "Verdict" },
    { type: "ul", items: ["Agents and vibe-coding tools: yes, curate carefully","ChatGPT/Perplexity traffic chasing: focus on sources, citations, and content quality instead"] },
    ],
  },
  {
    slug: "server-logs-for-ai-search",
    title: "Why server logs are crucial for AI search strategy",
    dek: "Training, indexing, and retrieval bots each unlock a different visibility layer — logs tell you which ones can reach you.",
    date: "Jun 30",
    year: "2026",
    publishedAt: "2026-06-30",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Log analysis used to be a niche SEO specialty. In AI search it's table stakes: if the wrong bots are blocked, no amount of content polish helps." },
    { type: "h2", text: "Three bot jobs" },
    { type: "ul", items: ["Training bots (e.g. GPTBot, Common Crawl consumers) — shape baseline knowledge","Search/indexing bots (e.g. OAI-SearchBot) — put you in the retrieval pool","User-query bots (e.g. ChatGPT-User) — fetch a page for a live request"] },
    { type: "h2", text: "How to read the mix" },
    { type: "p", text: "Healthy patterns show all three types. Check depth — if bots only hit the homepage, internal linking or crawl barriers are hiding the pages you want cited. Pair crawl frequency with citation tracking: often-crawled, rarely-cited URLs are prime optimization candidates — or signs your prompt set is incomplete." },
    { type: "h2", text: "Order of operations" },
    { type: "ol", items: ["Confirm robots.txt isn't blocking bots you need","Verify training, search, and user-query activity","Diff crawls vs citations in Anny","Only then deep-dive content quality"] },
    ],
  },
  {
    slug: "listicle-rank-effect",
    title: "The listicle rank effect on AI brand visibility",
    dek: "Across hundreds of thousands of AI responses, position inside cited third-party listicles correlates with mention rate and answer rank.",
    date: "May 14",
    year: "2026",
    publishedAt: "2026-05-14",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "AI engines treat ranked roundups as recommendation inputs. Being in the listicles they actually cite correlates with whether you're mentioned — and where you appear in the answer." },
    { type: "h2", text: "What holds across markets" },
    { type: "ul", items: ["Inclusion in frequently cited third-party listicles lifts visibility","Higher listicle rank associates with earlier answer position","Mention count is a noisier signal — don't use it alone","Returns diminish after a handful of strong placements"] },
    { type: "h2", text: "Market nuance" },
    { type: "p", text: "Emerging categories show sharper drop-offs below #1. Established SaaS gets a big lift from mere inclusion. Regulated niches may have few trusted publishers — win those, don't spray everywhere." },
    { type: "h2", text: "Engine nuance" },
    { type: "p", text: "Tighter-retrieval engines (often ChatGPT-like) amplify each top listicle more. Broader-retrieval Google AI surfaces dilute single-source impact — cast a slightly wider net." },
    { type: "h2", text: "Playbook" },
    { type: "ol", items: ["Track commercial prompts across engines in Anny","Filter cited sources to recurring listicles","Prioritize gaps where competitors appear and you don't","Give publishers evidence: reviews, comparisons, pricing clarity","Report visibility and position separately"] },
    ],
  },
  {
    slug: "citation-rate-benchmarks",
    title: "What does a good citation rate look like?",
    dek: "Benchmarks from over a million AI citations across ChatGPT, AI Mode, and Perplexity — retrieval is not citation.",
    date: "Feb 27",
    year: "2026",
    publishedAt: "2026-02-27",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "A retrieval means your page entered the candidate set. A citation means it was actually used in the answer. Citation rate connects the two — and healthy targets differ wildly by model." },
    { type: "h2", text: "Platform benchmarks" },
    { type: "ul", items: ["ChatGPT: generous — treat 2.0+ as a strong bar; top URLs soak up disproportionate citations","Google AI Mode: conservative — most URLs sit below 1.0; 1.1–1.5 is a solid aim","Perplexity: polarized — many URLs never cited in-answer; 1.5–2.0 means you're in the favored set"] },
    { type: "h2", text: "Intent and content type" },
    { type: "p", text: "Informational and commercial intents concentrate citations on fewer URLs. Listicles punch above their weight on ChatGPT; AI Mode favors official product/category pages more evenly." },
    { type: "h2", text: "How to use this" },
    { type: "p", text: "Benchmark by platform inside Anny. Don't average ChatGPT generosity with Perplexity stinginess into one meaningless KPI." },
    ],
  },
  {
    slug: "top-domains-cited-by-ai",
    title: "Top domains cited by AI search",
    dek: "From tens of millions of sources: Reddit, YouTube, LinkedIn, Wikipedia, and review sites keep winning — with platform twists.",
    date: "Mar 31",
    year: "2026",
    publishedAt: "2026-03-31",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "AI doesn't invent citations from nowhere. Across large multi-engine samples, a familiar cast dominates: Reddit, YouTube, LinkedIn, Wikipedia, Forbes, G2, Yelp, Facebook, Medium, TechRadar." },
    { type: "h2", text: "Platform twists" },
    { type: "ul", items: ["Google AI Mode / Overviews: heavy YouTube + social (Facebook, Yelp)","ChatGPT: Wikipedia, Reddit, Forbes, TechRadar, LinkedIn","Perplexity: Reddit, YouTube, LinkedIn, Wikipedia, G2"] },
    { type: "h2", text: "What to do" },
    { type: "p", text: "Maintain authentic Reddit and YouTube presence (review transcripts). Treat LinkedIn executive posts as citable artifacts. Keep review profiles accurate. Diversify — Reddit blackouts have happened before." },
    { type: "p", text: "Then ignore the generic top 10 and open Anny's domain view for your prompts. Hotels aren't SaaS; your Booking.com equivalent matters more than Medium." },
    ],
  },
  {
    slug: "self-promotional-listicles",
    title: "Self-promotional listicles still get cited — that doesn't make them smart",
    dek: "Across 232k citations in software niches, ~11% still come from brands ranking themselves #1. Risks remain.",
    date: "Mar 3",
    year: "2026",
    publishedAt: "2026-03-03",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Self-promo listicles — 'best tools' posts that crown the author's product — remain visible in AI citations. In a 12-week software-review study, roughly one in ten citations came from that pattern. ChatGPT ran much lower (~4%) than Google AI Mode and Perplexity (~10–11%). No clear systemic clampdown showed in that window." },
    { type: "h2", text: "Still not recommended" },
    { type: "ul", items: ["Reputational risk as buyers get savvier","Algorithmic risk SEO leaders have warned about for years","Better ROI from third-party listicles and real reviews"] },
    { type: "p", text: "Anny helps you see when competitors lean on self-promo sources — and when earned placements move your metrics instead." },
    ],
  },
  {
    slug: "risk-of-ai-generated-content",
    title: "The real risk of AI-generated content",
    dek: "Mass-produced AI pages can tank Google rankings — and because models ground on search, AI visibility falls with them.",
    date: "Feb 25",
    year: "2026",
    publishedAt: "2026-02-25",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Teams racing to publish raw AI blogs for ChatGPT mentions often damage the Google rankings that still feed AI grounding. When a site's organic visibility collapses, citations in ChatGPT, AI Mode, and Overviews tend to follow." },
    { type: "h2", text: "Why Google pain becomes AI pain" },
    { type: "p", text: "AI Overviews and AI Mode inherit Google's ranking world. ChatGPT and others still lean on web search. One quality hit propagates." },
    { type: "h2", text: "Safe use of AI in content" },
    { type: "ul", items: ["Assist ideation, outlining, editing — don't ship unedited slop","Add original research, experience, and opinions models can't copy-paste","Ask: would I read this? Does it add information gain?"] },
    { type: "p", text: "Anny can show citation drops after a content binge. Fix quality before you scale volume." },
    ],
  },
  {
    slug: "using-mcp-for-geo",
    title: "Using MCP for SEO, GEO, and AEO workflows",
    dek: "Connect Anny to Claude (and friends) so visibility audits, gap lists, and weekly client summaries run as conversations.",
    date: "Jun 11",
    year: "2026",
    publishedAt: "2026-06-11",
    category: "Product",
    body: [
    { type: "p", text: "Model Context Protocol (MCP) lets assistants call your tools. For GEO teams, that means asking Claude to pull visibility deltas, list fanouts, or draft a client update from live Anny data — instead of exporting CSVs by hand." },
    { type: "h2", text: "Workflows that stick" },
    { type: "ul", items: ["Weekly agency loop: every client project → visibility/SoV/sentiment vs last week → Slack + one-slide deck","Fanout mining: sample prompts containing a topic, summarize injected terms, propose content rewrites","Source gaps: URLs with high competitor mentions and zero you"] },
    { type: "h2", text: "Guardrails" },
    { type: "p", text: "Treat model suggestions as drafts. Keep humans on outreach tone and factual claims. Scope MCP tokens to the workspaces each teammate should see." },
    { type: "p", text: "Anny's API and MCP access on agency plans exist for exactly this operating model." },
    ],
  },
  {
    slug: "ai-shopping-analytics",
    title: "AI shopping analytics: measuring product recommendations",
    dek: "When ChatGPT and Google recommend products, classic ecommerce analytics miss the decision. Here's what to track instead.",
    date: "Jun 17",
    year: "2026",
    publishedAt: "2026-06-17",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "AI shopping surfaces recommend products inside the answer — sometimes with structured product data, sometimes as narrative shortlists. Referral tags rarely capture the influence." },
    { type: "h2", text: "KPIs for product brands" },
    { type: "ul", items: ["Share of recommendation prompts where your SKU/brand appears","Position in recommended sets","Which retailers or review URLs get cited alongside you","Self-reported discovery in post-purchase surveys"] },
    { type: "h2", text: "Operational tips" },
    { type: "p", text: "Keep product schema accurate, reviews fresh, and comparison pages honest. Track shopping-intent prompt tags separately in Anny so category research doesn't drown SKU visibility." },
    ],
  },
  {
    slug: "chatgpt-shopping-recommendations",
    title: "How ChatGPT shopping works — and how to get recommended",
    dek: "Product discovery inside chat blends training knowledge, live search, and merchant signals. Optimize the inputs you control.",
    date: "Jun 19",
    year: "2026",
    publishedAt: "2026-06-19",
    category: "Webinar Recap",
    body: [
    { type: "p", text: "ChatGPT product recommendations aren't a single algorithm you can game with one meta tag. They combine what the model already knows, what live search returns, and structured merchant/review evidence." },
    { type: "h2", text: "Levers that move recommendations" },
    { type: "ul", items: ["Clear product pages that render without heavy JS dependence","Third-party reviews and listicles the fanouts already chase","Accurate pricing and availability signals where merchant feeds apply","Brand consistency across Wikipedia, LinkedIn, and major retailers"] },
    { type: "h2", text: "Measure before you scale spend" },
    { type: "p", text: "Instrument recommendation prompts in Anny, then invest in the sources that already shape answers in your category." },
    ],
  },
  {
    slug: "reading-sources-in-anny",
    title: "How to get the most out of sources in Anny",
    dek: "Domains, URLs, gap scores, and model filters — a field guide to the Sources workspace.",
    date: "Jul 15",
    year: "2025",
    publishedAt: "2025-07-15",
    category: "Product",
    body: [
    { type: "p", text: "Sources is where GEO stops being theoretical. Every answer Anny captures lands with the URLs that shaped it." },
    { type: "h2", text: "Start at the domain level" },
    { type: "p", text: "See which publishers dominate your prompt set. Compare your domain's used rate and average citations against Reddit, review sites, and competitors." },
    { type: "h2", text: "Drill into URLs" },
    { type: "p", text: "Filter to your domain for refresh candidates. Filter to competitor mentions + your absence for outreach queues. Toggle ChatGPT vs AI Mode — the leaderboards diverge." },
    { type: "h2", text: "Act" },
    { type: "ul", items: ["Refresh high-retrieval low-citation pages","Pitch multi-model listicles where you're missing","Fix sentiment-driving review URLs"] },
    ],
  },
  {
    slug: "chatgpt-deep-research-logs",
    title: "How ChatGPT Deep Research reads your site",
    dek: "What server logs reveal when long-running research agents fetch, revisit, and cite your pages.",
    date: "Jun 22",
    year: "2026",
    publishedAt: "2026-06-22",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Deep Research-style agents don't behave like a single Googlebot hit. Logs show bursts of user-agent fetches, revisits to hub pages, and selective reading of docs-like URLs." },
    { type: "h2", text: "Implications" },
    { type: "ul", items: ["Critical explanations should be in static, crawlable HTML","Hub pages and clear IA help agents navigate","Blocked user-query bots break 'summarize this URL' and research flows"] },
    { type: "p", text: "Correlate Deep Research citations in Anny with log lines for the same URLs to see whether access or content quality is the bottleneck." },
    ],
  },
  {
    slug: "reddit-translated-pages-ai-visibility",
    title: "Translated Reddit is winning AI citations",
    dek: "Machine-translated Reddit pages surface in AI answers more than many brands expect — monitor and participate carefully.",
    date: "Jun 22",
    year: "2026",
    publishedAt: "2026-06-22",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Reddit already dominates many citation leaderboards. Machine-translated Reddit mirrors and localized copies extend that influence into non-English answers — sometimes outranking local publishers." },
    { type: "h2", text: "What brands should do" },
    { type: "ul", items: ["Monitor Reddit threads (and translations) that mention you","Respond with useful, non-astroturfed context where appropriate","Don't rely on translated mirrors you don't control for accurate product claims","Track Reddit-derived citations as their own source class in Anny"] },
    ],
  },
  {
    slug: "universal-commerce-protocol",
    title: "Universal Commerce Protocol: what it means for ecommerce",
    dek: "A commerce-oriented protocol layer is emerging for agents. Here's how merchandisers should think about readiness.",
    date: "Jan 16",
    year: "2026",
    publishedAt: "2026-01-16",
    category: "News",
    body: [
    { type: "p", text: "As assistants move from recommending products to helping complete purchases, shared commerce protocols matter the way MCP matters for tools: agents need predictable ways to discover catalog, price, and checkout capabilities." },
    { type: "h2", text: "Practical readiness" },
    { type: "ul", items: ["Keep product data clean and machine-readable","Expose clear policies (shipping, returns) in crawlable form","Watch how AI shopping answers cite your merchant surfaces today"] },
    { type: "p", text: "Visibility in recommendation prompts remains the top of funnel even as protocols mature — track both in Anny." },
    ],
  },
  {
    slug: "ai-search-focus-2026",
    title: "What marketing teams should focus on for AI search in 2026",
    dek: "A practical priority stack: measurement, sources, content quality, and model-specific playbooks — not another acronym war.",
    date: "Jan 14",
    year: "2026",
    publishedAt: "2026-01-14",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "2026 rewards teams that operationalize AI visibility instead of debating whether to call it GEO." },
    { type: "h2", text: "Priority stack" },
    { type: "ol", items: ["Instrument visibility, position, and sentiment across ChatGPT, Overviews, AI Mode, Gemini","Map and win the third-party sources those engines cite","Ship specific, structured, experience-rich content — not AI slop at scale","Keep JavaScript-critical content crawlable","Run weekly agency or in-house loops with clear actions"] },
    { type: "p", text: "Anny exists to make that stack measurable." },
    ],
  },
  {
    slug: "chatgpt-search-market-share",
    title: "The real search engine market share of ChatGPT",
    dek: "ChatGPT matters enormously as a decision surface — even when classic 'search share' charts understate it.",
    date: "Oct 19",
    year: "2025",
    publishedAt: "2025-10-19",
    category: "GEO Know-How",
    body: [
    { type: "p", text: "Comparing ChatGPT to Google on click-share alone misses the point. Much of ChatGPT's influence never becomes a click. Treat it as a parallel discovery and decision channel with its own measurement." },
    { type: "h2", text: "How to think about share" },
    { type: "ul", items: ["Track branded and category prompt visibility, not only referrals","Survey customers for AI-assisted discovery","Compare model-level visibility, not a single blended score"] },
    { type: "p", text: "Google's AI surfaces may win on raw reach; ChatGPT still shapes consideration for many B2B and consumer categories. Measure both in Anny." },
    ],
  }
];

export function getAllPosts(): BlogPost[] {
  return [...posts].sort((a, b) =>
    a.publishedAt < b.publishedAt ? 1 : a.publishedAt > b.publishedAt ? -1 : 0,
  );
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return posts.find((post) => post.slug === slug);
}

export function getPostSlugs(): string[] {
  return posts.map((post) => post.slug);
}
